package main

import "testing"

func TestNumPotionsNeededExample(t *testing.T) {
  input := "ABBAC"
  expected := 5

  result := numPotionsNeeded(input)

  if expected != result {
    t.Errorf("numPotionsNeeded(%s) = %d; want %d", input, result, expected)
  }
}

func TestNumPotionsNeededActual(t *testing.T) {
  input := "CCCCAABBAABABBCAAACBCCBAACBBBACCBAAAAACACABACCCCBCCAABACCCBCBCBCCCAACBBCCCBACCABABBABCBBABAABBAACBABACBCCBBCACBACAAACAAABABAABBABCCABABCBBBBCCABABCBAAABCBACACACCAABBBCBBBAAABABBABABCACBCBCABABCAACCBACAACAABAABBBBCAACCABACCBCBBCACACACBCAABCCABBACCBACBCACBABBACABCAABABAACBCCBCBCCABBBABCBACCABCCAACCCAACBBABCAAAABCAAABBCABCABBBAABCBCBABBCCBCACBCCBAABBACACAABBCBBACABBACCBCCBCBABCABBCBCAABBAACACCBABCAABCCABCACAABBAACAACBACBABCAACAABBBCACAABBAACCABAAABAABABCBABBBBCBAABBBAAAACACCACBAAABABBAAAAACACCCBBCCCCBCCABBBCCBCBBCCBACABABCCBBABBAAABBCCBAABBACAAAACCBBABABBCBABBBBBCABCBBCAABBBBCCCBCACABCBCACBCBBAACCABBCBCBACBCACCBBABCCCBAAACBBACCCCBAABCBACACBBBACCABCACACCBBCBCBBCBCACABCACCABCBCCCACABCCBBBBBCACBBAAAACBBCAAAAAACAABBABCBBBBABBBAABBCCCBACCBACCBACACAACBABBCABBABCABCABACAAABBBCBCBABBBCACBAABABACAAAAABCBBABBBABCAABACCAACBBABCAACAACBBACABCCCCAABCABCACACBBCCCACBBCABBACAAACBABCCCBCBBCAABBBBAACCAAABBCCABCBACBBBABACCACACAABABABCCCCAACBBCACBCABACBBCCBACCBCBAAAAABAAACABCACBBCAAAACBCCCCBCBCABABCAACACABAAB"
  expected := 1280

  result := numPotionsNeeded(input)

  if expected != result {
    t.Errorf("numPotionsNeeded(%s) = %d; want %d", input, result, expected)
  }
}
