package main

import "testing"

func TestDay1P1Example(t *testing.T) {
	input := `..........
..###.##..
...####...
..######..
..######..
...####...
..........`

	expected := 35

	result := Excavate(input)

	if expected != result {
		t.Errorf("Excavate(\"%s\") = %d; want %d", input, result, expected)
	}
}

func TestDay1P1Actual(t *testing.T) {
	input := `..............................
..............................
..............#...............
.............##...............
..........##..####............
..........#########...........
........#############.........
.......###############........
........###########..#........
.........#.#######............
..............#.###...........
.................##...........
................##............
..............................`

	expected := 126

	result := Excavate(input)

	if expected != result {
		t.Errorf("Excavate(\"%s\") = %d; want %d", input, result, expected)
	}
}
